version: '3'
volumes:
  BlogDbData:
services:
  database:
    image: "postgres:10-alpine"
    ports:
      - 1234:5432
    environment:
      POSTGRES_USER: usr_blog
      POSTGRES_PASSWORD: 12345678
      PGPASSWORD: 12345678
      POSTGRES_DB: mysite_blog
      PGDATA: /db_data
    volumes:
      - BlogDbData:/db_data