# Generated by Django 3.2.3 on 2021-06-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210604_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro_image',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=500, null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
