# Generated by Django 3.2.4 on 2021-07-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام کالا')),
                ('description', models.TextField(help_text='متن نمایشی برای توصیف محصول', verbose_name='توضحیات محصول')),
                ('price', models.PositiveIntegerField(db_index=True, default=0)),
                ('qty_in_stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='آیا این محصول فروخته میشود؟', verbose_name='آیا فعال است؟')),
                ('type', models.CharField(choices=[('JPEG', 'عکس با کیفیت معمولی'), ('PSD', 'فایل فوتوشاپ'), ('AI', 'فایل ایلوستریتور'), ('TEXT', 'فایل ورد'), ('PRINT', 'چاپ روی کاغذ')], max_length=100, verbose_name='نوع محصول')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
    ]
